### ISSUE TITLE
Specific Directions for Perlmutter at NERSC? 

### ISSUE THREAD

**Issue by etpalmer63** [openhackathons-org/End-to-End-AI-for-Science#6]
Hi,

I'm assisting a user who is trying to work through this material on Perlmutter at NERSC. I was wondering if anyone has notes on Perlmutter specific directions they could share for getting setup on the machine. 

Thank you!

Erik

**Comment by aswkumar99** [comment]
Hi @etpalmer63 , 

There are no Perlmutter-specific instructions; the repository has been recently updated to reflect the GPU requirement; while Omniverse is not guaranteed to work on A100 GPU, the modulus material can be used separately with a container Modulus from NVIDIA NGC. 

If you are facing a specific issue, kindly add it here, so I can understand it better and assist you. 

Thank you.
